### ISSUE TITLE
Update Assignment model to reflect new settings

### ISSUE THREAD

**Issue by jamesaevans** [codepost-io/codepost-python#17]
The codePost API has been updated to include several new fields, mostly reflecting new settings. To work with these fields via the SDK, those new fields need to be added to the SDK's `Assignment` model.

The new fields are:
* `allowStudentUpload`: boolean,
* `uploadDueDate`: string | null,
* `allowRegradeRequests`: boolean,
* `regradeDeadline`: string | null
* `templateMode`: boolean,
* `fileTemplates`: list of IDs,
* `collaborativeRubricMode`: boolean
* `hideGradersFromStudents`: boolean,
*  `forcedRubricMode`: boolean,
* `commentFeedback`: boolean,
* `liveFeedbackMode`: boolean,
* `additiveGrading`: boolean

**Comment by jlumbroso** [comment]
With the exception of the field `templateMode` this seems to have been addressed by https://github.com/codepost-io/codepost-python/commit/cfd8a49e3876e8d175dd0241572ff6c50714d348#diff-a18b00b07d6ddf47b35d2f71d7183794.

@jamesaevans I tried to look at doc for `templateMode` in the API documentation, however it is not there.
https://docs.codepost.io/reference#the-assignment-object

Should it be added to the documentation? (It exists in the API models.)
