### ISSUE TITLE
Can't iterate over my_course.assignments

### ISSUE THREAD

**Issue by jamesaevans** [codepost-io/codepost-python#21]
Using Python 3.6, doing so fails with
```
File "/usr/local/lib/python3.6/dist-packages/codepost/models/abstract/api_resource.py", line 68, in __getattribute__
return super(AbstractAPIResource, self).__getattribute__(item)
File "/usr/local/lib/python3.6/dist-packages/codepost/models/abstract/api_resource_metaclass.py", line 97, in __bound_getitem
type(field_type) is _typing._GenericAlias and
AttributeError: module 'typing' has no attribute '_GenericAlias'
```

Thanks to @niemasd for reporting!

**Comment by niemasd** [comment]
For context, here is a code snippet to reproduce it:

```python
codepost_course = codepost.course.retrieve(id=args.course_id) # user passes in args.course_id
codepost_assignment = None
for a in codepost_course.assignments:
    if a.name.strip() == args.assignment_name.strip(): # user passes in args.assignment_name
        codepost_assignment = a; break
if assignment is None:
    raise ValueError("Unable to find assignment with name: %s" % args.assignment_name.strip())
```

I got the same error from just printing ``codepost_course.assignments`` as well

**Comment by niemasd** [comment]
Btw, I'm on Python 3.6.8, and it seems like it may be an issue with recent versions of Python 3 (e.g. https://github.com/zalando/connexion/issues/739)

**Comment by niemasd** [comment]
Not sure if it's unsafe to do this, but I circumvented the issue by editing `codepost/models/abstract/api_resource_metaclass.py`. Specifically, I changed that line (97) from

```python
type(field_type) is _typing._GenericAlias and
```

to

```python
hasattr(field_type, '_name') and
```

**Comment by jamesaevans** [comment]
You're right that this bug is a version-compatibility issue. I can reproduce the error in Python 3.6.x but not Python 3.7.x.

After some digging, it seems like this issue is a consequence of the fact that we're relying on a Python-3.7-specific pattern for checking type compatibility (see discussion [here](https://github.com/python/typing/issues/570)). Even though this pattern works in Python 3.7 (as noted in the thread), we shouldn't rely on accessing an internal property of the `typings` library to do our work. 

So we'll investigate a way to replace that line (97) with a version that is both backwards-compatible with Python 3.6 and less fragile.

> Not sure if it's unsafe to do this, but I circumvented the issue by editing codepost/models/abstract/api_resource_metaclass.py. Specifically, I changed that line (97) from

This should work for the time being while waiting on a PR!

**Comment by jlumbroso** [comment]
@niemasd Sorry for only belatedly stepping in. Glad to see using our SDK!

**First,** regarding your sample snippet, thanks so much for providing it. I wanted to note that this:
```python
import codepost
codepost_course = codepost.course.retrieve(id=args.course_id) # user passes in args.course_id
codepost_assignment = None
for a in codepost_course.assignments:
    if a.name.strip() == args.assignment_name.strip(): # user passes in args.assignment_name
        codepost_assignment = a; break
if assignment is None:
    raise ValueError("Unable to find assignment with name: %s" % args.assignment_name.strip())
```
Could also be written like this:
```python
import codepost
course = codepost.course.list_available(name="COURSE1", period="Spring2020")[0]
assignment = course.assignments.by_name("Assignment 1")
```

**Second,** I wanted to explain a bit more about this bug. This bug has to do with the fact that in the SDK, the Python object are generated from abstract models specified as a dictionary. For instance, this is approximately how the [`Files` model is defined](https://github.com/codepost-io/codepost-python/blob/4c2ca94156eb4947be2e9948622f35fe8501a00f/codepost/models/files.py):
```python
import typing
class Files(...):
    # ...
    _FIELDS = {
        'name': (str, 'The name of the file.'),
        'code': (str,
        'The contents of the file. Accepts unicode-encoded strings, and will render newlines.'),
        'extension': (str,
        "The file extension. This field determines how the File's code will be syntax-highlighted."),
        'submission': (int, "The ID of the file's parent Submission."),
        'comments': (typing.List[_comments.Comments], 'The IDs of all comments applied to this file.'),
        'path': (str, 'An optional file path to indicate a directory structure within a submission.'),
        # ...
    }
    # ...
```
The foreign key relationship to `comments` is provided using the abstract type construction `typing.List`, i.e., in `typing.List[_comments.Comments]`. The factory code in the `abstract` sub-module then tries to read this specification to figure out what kind of object to create dynamically. The `_GenericAlias` is how Python implements the typing hints, and there was a big non-backwards compatible change Python 2.x, and Python 3.6< and 3.7+.

The logic for this has now been abstracted into two methods, [`detect_list_type()` and `is_type_variable()`](https://github.com/codepost-io/codepost-python/blob/78912d00bd33331484a123e8a4718c0be647d06c/codepost/models/abstract/api_resource_metaclass.py#L45-L111). Hopefully this way, it will be easier to maintain, easier to document, and as I expand the testing coverage, we can make sure that that functionality produces the right result no matter the Python version used.

Thanks again for reporting this issue!
