### ISSUE TITLE
Load Lazy object on print

### ISSUE THREAD

**Issue by jamesaevans** [codepost-io/codepost-python#24]
Currently, printing a lazily-loaded child object prints something that looks like:
```
<Lazy[Object] loaded=False: None>
```

I suspect clients have two goals when printing objects:
(1) They want to view all fields easily (probably especially common when using the SDK from a shell)
(2) They want to confirm whether they loaded the correct object

Neither is possible with the current approach, which only confirms the _type_ of the printed object.

To solve either, we need to load lazy objects on print (the codePost API doesn't support loading on a field-by-field basis). 

To solve (1), we could print the entire representation of the newly loaded object. To solve (2), we could designate a primary key for each object and print only that key.

**Comment by jlumbroso** [comment]
@jamesaevans You are so right about this. I originally thought that it may be overkill (and result in many API calls), but I think the main point of REPL in Python is to be able to see the data you're manipulating. I am having a session with the SDK right now and it is painful having to force-load the lazy objects.

**Comment by jlumbroso** [comment]
@jamesaevans Just added an internal parameter, by default set to `True`, called `_LAZY_LOAD_ON_REPR`. This will trigger a loading of lazy objects as they are about to be printed. It can be turned off in case someone is dealing with really time intensive datasets.

<img width="1089" alt="Screen Shot 2020-03-17 at 10 33 01 AM" src="https://user-images.githubusercontent.com/11770469/76866676-d8a05700-683a-11ea-982d-dc940ef5df03.png">
